version: '3'

services:
  app:
    container_name: book-library
    depends_on:
      - postgres
    # build:
    #   context: .
    image: golang:1.18
    # command: "go mod download && go build -o /book-library && /book-library"
    command: "sh ./run.sh"
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    container_name: book-library-db
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: qwer1234
      POSTGRES_USER: qwer
      POSTGRES_DB: book

volumes:
  db:
